import { defineConfig } from 'orval';

export default defineConfig({
  wade: {
    input: {
      target: '../internal/server/openapi/swagger.json'
    },
    output: {
      target: 'src/api/generated/wade.ts',
      client: 'fetch',
      mode: 'single',
      urlEncodeParameters: true,
      override: {
        header: () => [
          'Generated by Orval.',
          'Do not edit manually.',
          'WADE API client generated from internal/server/openapi/swagger.json.'
        ],
        mutator: {
          path: './src/api/httpClient.ts',
          name: 'wadeFetch'
        },
        fetch: {
          includeHttpResponseReturnType: false
        }
      }
    }
  }
});
